server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Ini trik sakti biar Nginx selalu ngebalikin ke index.html kalau rute gak ketemu
        try_files $uri $uri/ /index.html;
    }
}